services:
  db:
    image: postgres:16-alpine
    container_name: tfo-webapp-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tfo_webapp_dev
    volumes:
      - tfo-webapp-pgdata:/var/lib/postgresql/data

volumes:
  tfo-webapp-pgdata:
